# Generated by Django 4.0.2 on 2023-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_timetable_dayweek_alter_timetable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ManyToManyField(null=True, to='base.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='timetable',
            field=models.ManyToManyField(to='base.Timetable', verbose_name='Дни учёбы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(to='base.Contacts', verbose_name='Кониакты учеников'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='base.Image', verbose_name='Дополнительные изображения'),
        ),
    ]
