# Generated by Django 4.0.2 on 2023-05-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_account_group_alter_group_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(null=True, to='base.Project'),
        ),
    ]
